apiVersion: apps/v1
kind: Deployment
metadata:
  name: becky
spec:
  selector:
    matchLabels:
      app: becky
      service: becky
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: becky
        service: becky
        tier: backend
    spec:
      containers:
        - name: becky
          image: becky:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
